{% set name = "mip" %}
{% set version = "1.17.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mip-{{ version }}.tar.gz
  sha256: 9da8074b80bd3ef788513d5a214ef832916d82aa66487da11a49c7da9f89d270

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - cffi >=1.15
      #- cbcbox >=2.929

test:
  imports:
    - mip
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h-g-s/cbcbox
  summary: "Short description of the cbcbox package."
  dev_url: https://github.com/h-g-s/cbcbox
  doc_url: https://github.com/h-g-s/cbcbox/tree/master/docs
  summary: Binary distribution of the CBC MILP solver (COIN-OR Branch and Cut)
  description: high-performance, self-contained Python distribution of the CBC MILP solver (COIN-OR Branch and Cut), built from the latest COIN-OR master branch.
  license: MIT
    #license_file: LICENSE

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
    - avoid_noarch
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/110080
    reason: Client request
  recipe-maintainers:
    - ianaobi
