{% set name = "cbcbox" %}
{% set version = "2.929" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/0c/85/2fef9c7c3054ebfb9b0e84fabbeac776a18514b025efa5abd768c889f560/cbcbox-2.929-py3-none-win_amd64.whl
  sha256: 0a91420befb965ec1763aab62d7908d3a89a51af845e2a4e05c09d99a67f1151

build:
  number: 0
  skip: true  # [not win]
  script: "{{ PYTHON }} -m pip install {{ name }}-{{ version }}-py3-none-win_amd64.whl -vv --no-deps --no-build-isolation"
  ignore_run_exports:
    - python
  missing_dso_whitelist:
    - "*/lib*.dll"
    - "*/zlib1.dll"

requirements:
  host:
    - python
    - pip
    - zlib >=1.2.13,<2.0.0a0
  run:
    - python
    - pip
    - zlib >=1.2.13,<2.0.0a0

test:
  imports:
    - cbcbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h-g-s/cbcbox
  summary: Binary distribution of the CBC MILP solver (COIN-OR Branch and Cut)
  description: High-performance, self-contained Python distribution of the CBC MILP solver (COIN-OR Branch and Cut), built from the latest COIN-OR master branch.
  #license_family: EPL
  #license: EPL 2.0
  dev_url: https://github.com/h-g-s/cbcbox
  doc_url: https://github.com/h-g-s/cbcbox/tree/master/docs

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
    - avoid_noarch
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/110080
    reason: Client request
  recipe-maintainers:
    - ianaobi
